development:
  url: "http://localhost:9200"
  log: log/elasticsearch.development.log
test:
  url: "http://localhost:9200"
  log: log/elasticsearch.test.log
production:
  url: "http://localhost:9200"
  log: log/elasticsearch.production.log
