development:
  url: "http://localhost:9200"
  index_prefix: "mapa76_dev"
  log: log/elasticsearch.development.log
test:
  url: "http://localhost:9200"
  index_prefix: "mapa76_test"
  log: log/elasticsearch.test.log
production:
  url: "http://localhost:9200"
  index_prefix: "mapa76_prod"
  log: log/elasticsearch.production.log
